config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  get 'contact_us', to: "contact#contact_us"
  post 'send_form', to: "contact#send_form"

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord

  has_many :rewardings, dependent: :destroy
  has_many :users, through: :rewardings, dependent: :destroy

  validates :title, presence: true, uniqueness: true

  class << self
    def find_by_rule(rule)
      Badge.find_by!(rule: rule)
    end
  end

  def count(user)
    user.rewardings.where("badge_id = ?", self.id).count
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :set_badges, only: %i[index]
  before_action :set_badge, only: %i[show edit update destroy]

  def index
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create

    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge.id), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge.id)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badges
    @badges = Badge.all
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    p params
    params.require(:badge).permit(:title, :file_name, :rule)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_badges, only: %i[index]

  def index
  end

  private

  def set_badges
    @badges = Badge.all
  end
end

app/views/admin/badges/_badge.html.erb
<tr class="text-center">
  <td class="align-middle"><%= badge.id %></td>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle"><%= badge.file_name %></td>
  <td class="align-middle"><%= badge.rule %></td>
  <td class="align-middle"><%= link_to t('.show_link'), admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('.edit_link'), edit_admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('.delete_link'),
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('.delete_confirm') }
    %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="row">
  <div class="col col-md-6">
    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <%= render 'shared/errors', resource: @badge %>

      <p class="form-group">
        <%= form.label :title %><br>
        <%= form.text_field :title, id: :badge_title, class: 'form-control' %>
      </p>

      <p class="form-group">
        <%= form.label :file_name %><br>
        <%= form.text_field :file_name, id: :badge_file, class: 'form-control' %>
      </p>

      <p class="form-group">
        <%= form.label :rule %><br>
        <%= form.text_field :rule, id: :badge_rule, class: 'form-control' %>
      </p>

      <p><%= form.submit class: 'btn btn-secondary'%></p>

    <% end %>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<h4 class="text-info my-3"><%= t('.edit_header', badge: @badge.title) %></h4>

<div class="row">
  <div class="col">
    <%= render 'form' %>
    <%= link_to t('.back_link'), admin_badges_path %>
  </div>
</div>

app/views/admin/badges/index.html.erb
<h4 class="text-info my-3"><%= t('.header') %></h4>

<p>
  <%= link_to t('.new_badge'), new_admin_badge_path, :class=>'btn btn-secondary' %>
</p>

<table class="table table-striped">
  <thead>
  <tr class="text-center">
    <th style="width: 50px"><%= t('.id') %></th>
    <th><%= t('.title') %></th>
    <th><%= t('.file_name') %></th>
    <th><%= t('.rule') %></th>
    <th colspan="3"><%= t('.actions') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render @badges %>
  </tbody>
</table>

<p class="py-3">
  <%= link_to t('.tests_link'), admin_tests_path %>
</p>

app/views/admin/badges/new.html.erb
<h4 class="text-info my-3"><%= t('.header') %></h4>

<%= render 'form' %>
<%= link_to t('.back_link'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<h4 class="text-info my-3"><%= t('.header', title: @badge.title) %></h4>

<p>
  <strong><%= t('.file') %></strong>
  <span><%= @badge.file_name %></span>
</p>
<p>
  <strong><%= t('.rule') %></strong>
  <span><%= @badge.rule %></span>
</p>

<p class="py-3">
  <%= link_to t('.edit_link'), edit_admin_badge_path(@badge) %> |
  <%= link_to t('.back_link'), admin_badges_path %>
</p>