config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  get 'contact_us', to: "contact#contact_us"
  post 'send_form', to: "contact#send_form"

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/controllers/admin/gists_controller.rb
class Admin::GistsController < Admin::BaseController

  def index
    @gists = Gist.all
  end

end

app/views/admin/gists/_gist.html.erb
<tr class="text-center">
  <td><%= gist.id %></td>
  <td><%= link_to "#{gist.question.body.truncate(25)}", admin_question_path(gist.question) %></td>
  <td><%= link_to "#{gist.url}", "#{gist.url}", target: "_blank" %></td>
  <td><%= gist.user.email %></td>
</tr>

app/views/admin/gists/index.html.erb
<h4 class="text-info my-3"><%= t('.header') %></h4>

<table class="table table-striped">
  <thead>
  <tr class="text-center">
    <th style="width: 50px"><%= t('.id') %></th>
    <th><%= t('.question') %></th>
    <th><%= t('.url') %></th>
    <th><%= t('.email') %></th>
  </tr>
  </thead>
  <tbody>
  <%= render @gists %>
  </tbody>
</table>

<p class="py-3">
  <%= link_to t('.back_link'), admin_tests_path %>
</p>