config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  get 'contact_us', to: "contact#contact_us"
  post 'send_form', to: "contact#send_form"

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any?%>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id} do %>
    <h3><%= t('.header', count: resource.errors.count) %>:</h3>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="row mt-3">
  <div class="col">
    <% flash.each do |key, message| %>
      <% if key == "notice" %>
        <%= content_tag :div, message, class: "alert alert-info", role: "alert" %>
      <% elsif key == "alert" %>
        <%= content_tag :div, message, class: "alert alert-danger", role: "alert" %>
      <% else %>
        <%= content_tag :div, message, class: "alert alert-#{key}", role: "alert" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer style="height: 8.75rem; bottom: 0" class="bg-light pt-3 text-center position-absolute w-100">
  <p>
    <span><%= current_year %>, </span>
    <span><%= github_url("Yulatax","test-guru")%> </span>
    <span>by Taxidi Yuliana</span>
  </p>
  <p>
    The project is developed for creation, administration and execution of different tests.
  </p>
  <p>
    <span><%= link_to "Project idea: online school Thinknetica", "http://www.thinknetica.com", target: "_blank" %> </span>
  </p>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">

  <div>
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    <%= link_to 'Rewards', badges_path, class: 'navbar-text ml-5' %>
    <%= link_to 'Contact Us', contact_us_path, class: 'navbar-text ml-5' %>
    <% if user_signed_in? && current_user.is_admin? %>
      <%= link_to 'To Admin Panel', admin_tests_path, class: 'navbar-text ml-5' %>
    <% end %>
  </div>

  <span class="navbar-text">
    <% if user_signed_in? %>
        Welcome, <b><%= current_user.first_name %></b> Guru |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to t('.sign_in'), new_session_path(resource_name) %> |
        <%= link_to t('.sign_up'), new_registration_path(resource_name) %>
    <% end %>
  </span>

</nav>