config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  get 'contact_us', to: "contact#contact_us"
  post 'send_form', to: "contact#send_form"

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answers_limit

  scope :correct, -> { where(correct: true ) }

  private

  def answers_limit
    errors.add(:limit, 'no more then 4 answers per question') if self.question.answers.count > 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :set_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@answer.question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to t('.show_link'), admin_answer_path(answer) %>
  <%= link_to t('.edit_link'), edit_admin_answer_path(answer) %>
  <%= link_to t('.delete_link'),
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: t('.delete_confirm') }
  %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit class: 'btn btn-secondary'%>
  </p>
<% end %>

app/views/admin/answers/edit.html.erb
<h4 class="text-info my-3"><%= t('.edit_answer_header') %></h4>

<p class="text-secondary">
  <%= @answer.question.body %>
</p>

<%= render 'form' %>
<%= link_to t('.back_link'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h4 class="text-info my-3"><%= t('.new_answer_header') %></h4>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>
<%= link_to t('.back_link'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h4 class="text-info my-3"><%= t('.title') %></h4>

<p class="text-secondary">
  <%= @answer.question.body %>
</p>

<p>
  <b><%= t('.answer_label') %></b>
  <%= @answer.body %>
</p>

<p>
  <b><%= t('.correct_label')%></b>
  <%= @answer.correct %>
</p>

<%= link_to t('.back_link'), admin_question_path(@answer.question) %>